FROM debian:stretch

RUN apt-get update && apt-get install -y \
	less puppet puppetmaster puppetmaster-passenger \
	puppet-module-puppetlabs-ntp puppet-module-puppetlabs-mysql \
	puppet-module-puppetlabs-stdlib
